/* Last Whistle — catalogs: locations, activities, items, opponents */
(function (root) {
  const SLOTS = ["Morning", "Afternoon", "Evening"];

  const BACKGROUNDS = [
    {
      id: "dock",
      name: "Crane kid",
      blurb: "You grew up on the gantries. Heavy hands, impatient feet.",
      stats: { str: 11, agi: 7, stm: 9, tec: 5 },
      style: "brawler",
    },
    {
      id: "courier",
      name: "Slip runner",
      blurb: "Manifests, alleys, and people who don't want to be found.",
      stats: { str: 7, agi: 11, stm: 8, tec: 7 },
      style: "mover",
    },
    {
      id: "night",
      name: "Night-school",
      blurb: "You studied footwork in a library copy of an old rulebook.",
      stats: { str: 7, agi: 8, stm: 8, tec: 11 },
      style: "technician",
    },
    {
      id: "galley",
      name: "Galley spare",
      blurb: "Years of double shifts. Your gas tank is a rumor.",
      stats: { str: 8, agi: 7, stm: 12, tec: 6 },
      style: "brawler",
    },
  ];

  const DISTRICTS = [
    { id: "quay", name: "THE QUAY" },
    { id: "yard", name: "THE YARD" },
    { id: "wharf", name: "THE WHARF" },
    { id: "deep", name: "DEEP WATER" },
  ];

  const LOCATIONS = {
    bunk: {
      id: "bunk",
      name: "Bunkhouse 4C",
      district: "quay",
      blurb: "A locker, a cot, a window that looks at cranes instead of sky.",
    },
    docks: {
      id: "docks",
      name: "Blackwater Docks",
      district: "quay",
      blurb: "Containers stacked like bad decisions. Pay is real. So are hernias.",
    },
    canteen: {
      id: "canteen",
      name: "Union Canteen",
      district: "quay",
      blurb: "Steam, tin trays, and stew that has seen things.",
    },
    alley: {
      id: "alley",
      name: "Bin Alley Circuit",
      district: "yard",
      blurb: "Fights under a leaking downspout. Purse in cash. Pride optional.",
    },
    rustgym: {
      id: "rustgym",
      name: "Rust Bucket Gym",
      district: "yard",
      blurb: "Bags that shed sand. A bell that lies about rounds.",
    },
    diner: {
      id: "diner",
      name: "The Last Whistle",
      district: "wharf",
      blurb: "Oz's diner. Coffee like tar. Gossip like scripture.",
    },
    market: {
      id: "market",
      name: "Night Market",
      district: "wharf",
      blurb: "Wraps, salve, gloves, and a man who will sell you a rumor.",
    },
    crane: {
      id: "crane",
      name: "Blue Crane Club",
      district: "wharf",
      blurb: "Neon, smoke, and fights they call exhibitions.",
    },
    temple: {
      id: "temple",
      name: "Iron Temple",
      district: "yard",
      blurb: "Old champions and older debts. Membership is a filter.",
    },
    arena: {
      id: "arena",
      name: "Harbor Arena",
      district: "deep",
      blurb: "The Commission's lights. The whistle everyone hears.",
    },
    barge: {
      id: "barge",
      name: "Pier 9 — Quiet Ledger",
      district: "deep",
      blurb: "A dark hull. A name that shouldn't be painted on anything.",
    },
  };

  const ACTIVITIES = [
    // Bunk
    {
      id: "sleep",
      loc: "bunk",
      name: "Sleep it off",
      tag: "Rest",
      energyMin: 0,
      desc: "End the day. Recover. Dream about horns and static.",
    },
    {
      id: "pushups",
      loc: "bunk",
      name: "Push-ups",
      tag: "Train",
      energyMin: 12,
      desc: "Slow. Each push-up is a little strength and a little stamina. Stop whenever you want.",
    },
    {
      id: "shadow",
      loc: "bunk",
      name: "Shadowbox the locker",
      tag: "Train",
      energyMin: 12,
      desc: "Each round is a little footwork and a little technique. You can stop mid-set.",
    },
    {
      id: "replay",
      loc: "bunk",
      name: "Replay Juno's tape",
      tag: "Story",
      energyMin: 0,
      once: "replayTape",
      desc: "The voicemail is six seconds of almost.",
    },
    {
      id: "tv",
      loc: "bunk",
      name: "Watch the box",
      tag: "Rest",
      energyMin: 0,
      desc: "Harbor news, bad soaps, a little of your spine back.",
    },
    {
      id: "fridge",
      loc: "bunk",
      name: "Fridge",
      tag: "Eat",
      energyMin: 0,
      desc: "Eat leftovers first. Work waits on a full stomach.",
    },
    {
      id: "home_bag",
      loc: "bunk",
      name: "Garage bag",
      tag: "Train",
      energyMin: 10,
      desc: "Each combo is mostly strength, a little technique. Hunger and energy drop while you hit.",
    },
    {
      id: "home_skip",
      loc: "bunk",
      name: "Skip in the garage",
      tag: "Train",
      energyMin: 8,
      desc: "Each set is agility and stamina. Stop when the rope starts to bore you.",
    },
    {
      id: "look_quay",
      loc: "bunk",
      name: "Look out on the quay",
      tag: "Look",
      energyMin: 0,
      desc: "Cranes, water, a bollard. Look for the horn.",
    },
    {
      id: "look_mug",
      loc: "bunk",
      name: "Juno's mug",
      tag: "Look",
      energyMin: 0,
      desc: "Still waiting for too much sugar.",
    },
    {
      id: "look_bench",
      loc: "bunk",
      name: "Workbench",
      tag: "Look",
      energyMin: 0,
      desc: "Tape, wrenches, a glove that lost its twin.",
    },
    {
      id: "look_note",
      loc: "bunk",
      name: "Scratch pad",
      tag: "Look",
      energyMin: 0,
      desc: "Juno's scratch pad. A real note, not a riddle.",
    },
    {
      id: "look_juno_bunk",
      loc: "bunk",
      name: "Juno's bunk",
      tag: "Look",
      energyMin: 0,
      desc: "Top bunk. Navy-wrong fold. Don't touch it.",
    },
    {
      id: "wash_sink",
      loc: "bunk",
      name: "Wash up",
      tag: "Rest",
      energyMin: 0,
      desc: "Cold water. Files a complaint with your face.",
    },
    {
      id: "kettle",
      loc: "bunk",
      name: "Boil the kettle",
      tag: "Rest",
      energyMin: 0,
      desc: "Tea that tastes like a pipe with manners.",
    },
    {
      id: "sit_sofa",
      loc: "bunk",
      name: "Nap on the sofa",
      tag: "Rest",
      energyMin: 0,
      desc: "Two hours. Energy back, a little hunger, a little mood. Not a night.",
    },
    // Docks
    {
      id: "haul",
      loc: "docks",
      name: "Haul crates",
      tag: "Work",
      energyMin: 22,
      desc: "Foreman Brant pays in cash and contempt.",
    },
    {
      id: "manifests",
      loc: "docks",
      name: "Sort manifests",
      tag: "Work",
      energyMin: 10,
      desc: "Light on the back, heavy on the eyes. Sometimes the paper lies.",
    },
    {
      id: "watch",
      loc: "docks",
      name: "Night watch",
      tag: "Work",
      energyMin: 18,
      slot: 2,
      desc: "Evening only. You walk the fence with a thermos and a rumor.",
    },
    {
      id: "overtime",
      loc: "docks",
      name: "Double shift (6h)",
      tag: "Work",
      energyMin: 28,
      desc: "After you haul once. Brant pays. Your hands file a complaint.",
    },
    {
      id: "locker",
      loc: "docks",
      name: "Juno's locker",
      tag: "Story",
      energyMin: 0,
      needFlag: "heardLocker",
      once: "openedLocker",
      desc: "Bay C, third from the horn. The lock still knows your birthday.",
    },
    // Canteen
    {
      id: "noodles",
      loc: "canteen",
      name: "Cup noodles ($3)",
      tag: "Eat",
      money: 3,
      desc: "Hot water and optimism.",
    },
    {
      id: "stew",
      loc: "canteen",
      name: "Union stew ($8)",
      tag: "Eat",
      money: 8,
      desc: "Mae says it builds character. It builds something.",
    },
    {
      id: "talk_mae",
      loc: "canteen",
      name: "Talk to Mae",
      tag: "Talk",
      energyMin: 0,
      desc: "Union steward. She files complaints like other people file punches.",
    },
    // Alley
    {
      id: "board",
      loc: "alley",
      name: "Fight board",
      tag: "Fight",
      energyMin: 0,
      desc: "Names, purses, and a seagull who judges your form.",
    },
    {
      id: "rope_alley",
      loc: "alley",
      name: "Jump the potholes",
      tag: "Train",
      energyMin: 14,
      desc: "Agility work if you don't mind an audience of cats.",
    },
    {
      id: "dumpster",
      loc: "alley",
      name: "Bin burger",
      tag: "Eat",
      energyMin: 0,
      desc: "Free food from the alley bins. Hunger yes. Health and mood no.",
    },
    // Gym
    {
      id: "join_rust",
      loc: "rustgym",
      name: "Pay Rust dues ($15 / week)",
      tag: "Gym",
      money: 15,
      desc: "Kade won't coach a tourist.",
    },
    {
      id: "bag",
      loc: "rustgym",
      name: "Heavy bag",
      tag: "Train",
      gym: "rust",
      energyMin: 18,
      desc: "Each combo is mostly strength. Hunger, energy, and interest drop while you hit. Stop anytime.",
    },
    {
      id: "spar",
      loc: "rustgym",
      name: "Spar a regular",
      tag: "Train",
      gym: "rust",
      energyMin: 22,
      desc: "Each exchange is technique, footwork, and gas. You can quit the spar mid-round.",
    },
    {
      id: "weights",
      loc: "rustgym",
      name: "Bent bar lifts",
      tag: "Train",
      gym: "rust",
      energyMin: 18,
      desc: "Each lift is strength and stamina. Put the bar down when you want to stop.",
    },
    {
      id: "skip",
      loc: "rustgym",
      name: "Skip rope",
      tag: "Train",
      gym: "rust",
      energyMin: 14,
      desc: "Each set is agility and stamina. Stop when your interest runs out.",
    },
    {
      id: "talk_kade",
      loc: "rustgym",
      name: "Talk to Kade",
      tag: "Talk",
      energyMin: 0,
      desc: "Former dock champ. Current maker of terrible tea.",
    },
    {
      id: "pads",
      loc: "rustgym",
      name: "Pads with Kade ($8)",
      tag: "Train",
      money: 8,
      energyMin: 10,
      desc: "Once a day. Each round is timing and footwork. Stop if you lose interest.",
    },
    // Diner
    {
      id: "coffee",
      loc: "diner",
      name: "Whistle coffee ($4)",
      tag: "Eat",
      money: 4,
      desc: "It is not coffee. It is a dare.",
    },
    {
      id: "plate",
      loc: "diner",
      name: "Dock plate ($14)",
      tag: "Eat",
      money: 14,
      desc: "Eggs, grease, and a pickle that has opinions.",
    },
    {
      id: "protein",
      loc: "diner",
      name: "Oz's protein pile ($22)",
      tag: "Eat",
      money: 22,
      desc: "Tomorrow's bag work will thank you. Your wallet will not.",
    },
    {
      id: "talk_oz",
      loc: "diner",
      name: "Talk to Oz",
      tag: "Talk",
      energyMin: 0,
      desc: "Cook, gossip switchboard, accidental detective.",
    },
    {
      id: "dishes",
      loc: "diner",
      name: "Wash the stack ($7)",
      tag: "Work",
      energyMin: 8,
      desc: "Two hours. Oz points. You become the stack.",
    },
    // Market
    {
      id: "shop",
      loc: "market",
      name: "Browse stalls",
      tag: "Shop",
      energyMin: 0,
      desc: "Gear, salve, and one honest scale.",
    },
    // Temple
    {
      id: "join_temple",
      loc: "temple",
      name: "Iron dues ($40 / week)",
      tag: "Gym",
      money: 40,
      desc: "They polish the bell. They do not polish you.",
    },
    {
      id: "temple_bag",
      loc: "temple",
      name: "Temple circuits",
      tag: "Train",
      gym: "temple",
      energyMin: 20,
      desc: "Better bags. Meaner mirrors.",
    },
    {
      id: "temple_spar",
      loc: "temple",
      name: "Spar a prospect",
      tag: "Train",
      gym: "temple",
      energyMin: 24,
      desc: "People who intend to be famous, soon.",
    },
    // Crane club
    {
      id: "crane_board",
      loc: "crane",
      name: "Exhibition board",
      tag: "Fight",
      energyMin: 0,
      desc: "Pretty lights. Ugly contracts.",
    },
    {
      id: "talk_lila",
      loc: "crane",
      name: "Find Neon Lila",
      tag: "Talk",
      energyMin: 0,
      desc: "If she's in, the room knows it.",
    },
    // Arena
    {
      id: "arena_board",
      loc: "arena",
      name: "Commission card",
      tag: "Fight",
      energyMin: 0,
      desc: "Silas Crowe prints names like invoices.",
    },
    // Barge
    {
      id: "sneak_barge",
      loc: "barge",
      name: "Slip the gangway",
      tag: "Story",
      energyMin: 20,
      desc: "Night water. Bad ideas. Maybe Juno.",
    },
  ];

  const ITEMS = {
    wraps: {
      id: "wraps",
      name: "Hand wraps",
      slot: "hands",
      price: 12,
      desc: "Fewer sprains. Slightly more dignity.",
      bonus: { tec: 1 },
    },
    scuffed: {
      id: "scuffed",
      name: "Scuffed gloves",
      slot: "hands",
      price: 35,
      desc: "Someone else's blood has been washed out. Probably.",
      bonus: { str: 1, tec: 1 },
    },
    harbor: {
      id: "harbor",
      name: "Harbor gloves",
      slot: "hands",
      price: 90,
      desc: "Commission surplus. They fit like a warning.",
      bonus: { str: 2, tec: 1 },
    },
    decks: {
      id: "decks",
      name: "Deck shoes",
      slot: "feet",
      price: 40,
      desc: "Grip on wet concrete and wet lies.",
      bonus: { agi: 2 },
    },
    boots: {
      id: "boots",
      name: "Ring boots",
      slot: "feet",
      price: 85,
      desc: "Ankle support and a whisper of professionalism.",
      bonus: { agi: 2, stm: 1 },
    },
    salve: {
      id: "salve",
      name: "Dock salve",
      price: 8,
      consumable: true,
      desc: "Smells like a shipwright's apology. Heals 22 HP.",
    },
    salts: {
      id: "salts",
      name: "Smelling salts",
      price: 15,
      consumable: true,
      desc: "Between rounds: +18 stamina.",
    },
    tape: {
      id: "tape",
      name: "Spare tape",
      price: 6,
      consumable: true,
      desc: "Use before a bout. Cuts injury chance.",
    },
    coil: {
      id: "coil",
      name: "Shortwave coil",
      price: 6,
      consumable: true,
      desc: "Oz asked. Weather needs a throat.",
    },
    noodles: {
      id: "noodles",
      name: "Cup noodles",
      price: 3,
      consumable: true,
      food: true,
      hunger: 28,
      energy: 4,
      mood: 4,
      desc: "Goes in the fridge. Eat at home.",
    },
    stew: {
      id: "stew",
      name: "Union stew",
      price: 8,
      consumable: true,
      food: true,
      hunger: 44,
      energy: 8,
      hp: 6,
      mood: 8,
      desc: "Mae's. Fridge, then eat.",
    },
    coffee: {
      id: "coffee",
      name: "Whistle coffee",
      price: 4,
      consumable: true,
      food: true,
      hunger: 6,
      energy: 14,
      mood: 2,
      desc: "A dare in a cup. Fridge.",
    },
    plate: {
      id: "plate",
      name: "Dock plate",
      price: 14,
      consumable: true,
      food: true,
      hunger: 58,
      energy: 10,
      hp: 10,
      mood: 12,
      desc: "Eggs and a pickle. Fridge.",
    },
    protein: {
      id: "protein",
      name: "Protein pile",
      price: 22,
      consumable: true,
      food: true,
      hunger: 40,
      energy: 6,
      hp: 8,
      mood: 6,
      buff: true,
      desc: "Training bonus. Fridge.",
    },
  };

  const SHOP = ["noodles", "stew", "coffee", "plate", "protein", "wraps", "scuffed", "harbor", "decks", "boots", "salve", "salts", "tape", "coil"];

  const OPPONENTS = {
    tommy: {
      id: "tommy",
      name: "Bin Rat Tommy",
      rank: "Alley",
      purse: 24,
      fee: 0,
      fameNeed: 0,
      loc: "alley",
      stats: { str: 7, agi: 9, stm: 8, tec: 4, hp: 88 },
      bias: ["press", "press", "stall", "box"],
      sprite: "scrappy",
      intro: "A seagull sits on the ropes. Tommy nods at it like it is his cutman.",
      win: "Tommy offers you a sandwich from a bag. You decline. The seagull does not.",
      lose: "You wake up next to a bin. Tommy says rent is still due.",
    },
    wren: {
      id: "wren",
      name: "Pipe Wren",
      rank: "Alley",
      purse: 32,
      fee: 0,
      fameNeed: 4,
      loc: "alley",
      stats: { str: 10, agi: 7, stm: 9, tec: 6, hp: 100 },
      bias: ["press", "box", "press", "press"],
      sprite: "heavy",
      intro: "Wren used to fit pipes. Your ribs are the next measurement.",
      win: "Wren shakes your hand like they mean it.",
      lose: "Your ribs have a new bruise. Wren files it under done.",
    },
    sal: {
      id: "sal",
      name: "Hook-Hand Sal",
      rank: "Alley",
      purse: 40,
      fee: 0,
      fameNeed: 10,
      loc: "alley",
      stats: { str: 9, agi: 10, stm: 10, tec: 8, hp: 108 },
      bias: ["counter", "box", "counter", "press"],
      sprite: "slick",
      intro: "Hook is a nickname. The hands are real.",
      win: "Sal grins. Tell Juno the docks still bite.",
      lose: "Sal taps your cheek. Come back when the ledger is heavier.",
    },
    nunzio: {
      id: "nunzio",
      name: "Brick Nunzio",
      rank: "Gym",
      purse: 36,
      fee: 0,
      fameNeed: 6,
      loc: "rustgym",
      gym: "rust",
      stats: { str: 12, agi: 6, stm: 11, tec: 5, hp: 120 },
      bias: ["press", "press", "stall", "press"],
      sprite: "heavy",
      intro: "Kade said don't let Nunzio walk you to the corner. That corner is his house.",
      win: "Nunzio laughs through a nosebleed. Kade's pet has teeth.",
      lose: "The corner was his house. You left on the floor.",
    },
    lila: {
      id: "lila",
      name: "Neon Lila",
      rank: "Club",
      purse: 70,
      fee: 10,
      fameNeed: 14,
      loc: "crane",
      stats: { str: 9, agi: 13, stm: 11, tec: 12, hp: 115 },
      bias: ["box", "counter", "box", "press"],
      sprite: "slick",
      intro: "Pink light. She fought Juno. She is not here to be kind.",
      win: "Lila touches gloves. Your sibling hit like that. Then they got quiet.",
      lose: "She helps you up. That is worse than the round.",
    },
    perry: {
      id: "perry",
      name: "Glassjaw Perry",
      rank: "Club",
      purse: 55,
      fee: 8,
      fameNeed: 18,
      loc: "crane",
      stats: { str: 11, agi: 11, stm: 9, tec: 10, hp: 96 },
      bias: ["press", "box", "press", "counter"],
      sprite: "scrappy",
      intro: "Everyone says Perry has a glass chin. Perry says he has timing.",
      win: "Perry sits down like a man remembering gravity.",
      lose: "Tonight it was the chin.",
    },
    vargas: {
      id: "vargas",
      name: "Crane Vargas",
      rank: "Commission",
      purse: 90,
      fee: 0,
      fameNeed: 0,
      loc: "arena",
      story: true,
      stats: { str: 14, agi: 10, stm: 13, tec: 9, hp: 140 },
      bias: ["press", "press", "box", "stall"],
      sprite: "heavy",
      intro: "Crowe's enforcer. He calls fighters inventory. He walked Juno toward the water.",
      win: "Vargas hits the canvas. Juno is cargo, he says. Cargo moves.",
      lose: "The lights are honest. You are not winning this fight.",
    },
    sophie: {
      id: "sophie",
      name: "Iron Sophie",
      rank: "Title",
      purse: 120,
      fee: 15,
      fameNeed: 28,
      loc: "arena",
      stats: { str: 13, agi: 12, stm: 14, tec: 13, hp: 150 },
      bias: ["box", "counter", "box", "press"],
      sprite: "slick",
      intro: "Temple champion. She nods once, like she is filing you under Later.",
      win: "Sophie: if you take Crowe's whistle, don't swallow it.",
      lose: "A clinic. You were the demonstration.",
    },
    crowe: {
      id: "crowe",
      name: "Silas Crowe",
      rank: "The Whistle",
      purse: 200,
      fee: 0,
      fameNeed: 0,
      loc: "arena",
      story: true,
      stats: { str: 15, agi: 13, stm: 15, tec: 14, hp: 165 },
      bias: ["box", "counter", "press", "box"],
      sprite: "boss",
      intro: "This is the night fight Juno warned you about. Crowe smiles like he already sold the ending.",
      win: "The whistle in his pocket is just metal. The man was the trap.",
      lose: "He does not knock you out. He catalogues you.",
    },
  };

  const RENT = { bunk: 35, flat: 70 };

  root.LW_CONTENT = {
    SLOTS,
    BACKGROUNDS,
    DISTRICTS,
    LOCATIONS,
    ACTIVITIES,
    ITEMS,
    SHOP,
    OPPONENTS,
    RENT,
  };
})(typeof window !== "undefined" ? window : global);
